### ISSUE TITLE
Add commit SHA to branch / edge images

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-server-docker#114]
This is similar to #46, but specifically focused on adding commit SHA details to branch / edge images. We should be able to capture environment / checkout details for these branch / edge workflows and pass through those details into the image.

**Comment by devinrsmith** [comment]
This feature could also be considered more widely solved via https://github.com/deephaven/deephaven-core/issues/3705; that said, there is still room for us to add deephaven-server-docker build sourced information, even if the above issue is completed.

**Comment by stanbrub** [comment]
Are you thinking of something like the following for the interim?
```
docker build --build-arg GIT_COMMIT=$(git rev-parse HEAD) -t my_image:$(git rev-parse HEAD) .
```
That would mean it's captured in the build log or a text file we add, but it would not be reachable in a native build.

**Comment by stanbrub** [comment]
Here's an example to set the deephaven-core commit hash to an environment variable in the docker image.  https://github.com/deephaven/deephaven-server-docker/compare/main...stanbrub:deephaven-server-docker:commit-hash-in-image?expand=1.  Not complete but shows something working.

**Comment by devinrsmith** [comment]
Yes, something like that. I think we want to ultimately propagate it into the LABEL field.

I would have hoped that the checkout action had an official output, but it looks like it doesn't (although, it seems like a pretty popular feature request, https://github.com/actions/checkout/issues/209).

**Comment by devinrsmith** [comment]
`org.opencontainers.image.revision` would be the best label; https://github.com/opencontainers/image-spec/blob/main/annotations.md
